## cachematrix consists of two functions:
##
## makeCacheMatrix, which creates a list of functions to:
##     set the value of a special matrix (set)
##     get the value of the matrix (get)
##     set the value of the matrix inverse (setInverse)
##     get the value of the matrix inverse (getInverse)
## and
##
## cacheSolve, which calculates the inverse of the special matrix created by makeCacheMatrix. 
## However, it first checks to see if the inverse has already been calculated. 
## If so, it gets the inverse from the cache, saving time. 
## Otherwise, it calculates the inverse of the data matrix sets the value of the inverse 
## in the cache by use of the setInverse function in makeCacheMatrix.

## makeCacheMatrix
## Usage: makeCacheMatrix(x) where x is a numeric matrix
##
## returns a list with elements - 
## $set, a function which sets the value of the matrix
## $get, a function which returns the value of the matrix
## $setInverse, a function which sets the inverse of the matrix in cache to a desired value
## $getInverse, a function which returns the value stored in the inverse matrix cache
##
## When makeCacheMatrix is first called, the inverse of the matrix is stored as NULL
## It also checks that the matrix is square and returns a warning if it is not as an inverse
## matrix can technically only be generated from a square matrix.

makeCacheMatrix <- function(x = matrix()) {
    ## test to see if matrix is square
    if (nrow(x) != ncol(x)) {
        warning("Matrix is not square.")
    }
    ## create NULL inverse
    inverse <- NULL
    ## set matrix and inverse in parent environment using <<-
    set <- function(y) {
        x <<- y
        inverse <<- NULL
    }
    ## get data from matrix
    get <- function() x
    ## set inverse data with data provided
    setInverse <- function(inverseOfMatrix) inverse <<- inverseOfMatrix
    ## return value stored as inverse matrix
    getInverse <- function() inverse
    
    ## Return a list of the internal functions so a calling function can access those methods.           
    list(set = set, get = get,
         setInverse = setInverse,
         getInverse = getInverse)    
}


## cacheSolve
## Usage: cacheSolve(x) where x is an object generated by makeCacheMatrix
##
## returns a matrix the inverse of the matrix stored in x.
## If x is not square the Moore-Penrose generalized inverse is returned
## If the inverse has not been stored before in the cache it generates it, otherwise
## it returns the value stored in the cache.
## An error will be generated if the matrix is not invertible.

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    ## determine whether cached inverse has been generated and return cached value if it has.
    inverse <- x$getInverse()
    if(!is.null(inverse)) {
        message("getting cached data")
        return(inverse)
    }
    ## Get matrix data
    data <- x$get()
    ## If matrix is not square generate a warning and find generalized inverse
    if (nrow(data) != ncol(data)) {
        library(MASS)
        warning("Matrix is not square. Moore-Penrose generalized inverse matrix result generated")
        inverse <- ginv(data, ...)
    } else {
        ## If square matrix find the inverse
        inverse <- solve(data, ...)
    }
    ## Set inverse in cache and return it
    x$setInverse(inverse)
    inverse    
}
